---
title: "nba"
output: html_document
date: "2024-01-14"
---

```{r, echo = FALSE}
library(knitr)
```


```{r, echo = FALSE}
library(reactable)
library(htmltools)
library(RColorBrewer)
library(DT)
library(tidyverse)
library(dplyr)
#https://projects.fivethirtyeight.com/nba-player-ratings/
```

```{r, echo = FALSE}
latest_raptor_player <- read.csv("datasets/latest_RAPTOR_by_player.csv") 
latest_raptor_team <- read.csv("datasets/latest_RAPTOR_by_team.csv") 
```

#Note : We can't reproduce the table perfectly because the positions must have been manually added in

```{r, echo = FALSE}
nba <- latest_raptor_player %>% 
  left_join(select(latest_raptor_team, player_name, team), by = "player_name") %>% 
  distinct()
```

```{r, echo = FALSE}
nba_gen <- nba %>% 
  select(player_name, season, team, mp, raptor_box_offense, raptor_box_defense, raptor_box_total,
 raptor_onoff_offense, raptor_onoff_defense, raptor_onoff_total, 
 raptor_offense, raptor_defense, raptor_defense, raptor_total, war_total) %>% 
  filter(mp >= 1137) %>% 
  arrange(-war_total)
```

#Note: No column for what position each player played

#Note: rounding is a bit off

#Note: number of rows does not match. 

```{r, echo = FALSE}
box_score_raptor <- c("raptor_box_offense", "raptor_box_defense", "raptor_box_total")
on_off_raptor <- c("raptor_onoff_offense", "raptor_onoff_defense", "raptor_onoff_total")
overall_raptor <- c("raptor_offense", "raptor_defense", "raptor_total", "war_total")

nba_gen <- nba_gen[, c("player_name", "season", "team", "mp", box_score_raptor, on_off_raptor, overall_raptor)]

# cols_to_round <- c("raptor_box_offense", "raptor_box_defense", "raptor_box_total",
#                     "raptor_onoff_offense", "raptor_onoff_defense", "raptor_onoff_total",
#                     "raptor_offense", "raptor_defense", "raptor_total")

#rounding all numeric columns: 
nba_gen$raptor_box_offense <- format(round(nba_gen$raptor_box_offense, 1), nsmall = 1)
nba_gen$raptor_box_defense <- format(round(nba_gen$raptor_box_defense, 1), nsmall = 1)
nba_gen$raptor_box_total <- format(round(nba_gen$raptor_box_total, 1), nsmall = 1)
nba_gen$raptor_onoff_offense <- format(round(nba_gen$raptor_onoff_offense, 1), nsmall = 1)
nba_gen$raptor_onoff_defense <- format(round(nba_gen$raptor_onoff_defense, 1), nsmall = 1)
nba_gen$raptor_onoff_total <- format(round(nba_gen$raptor_onoff_total, 1), nsmall = 1)
nba_gen$raptor_offense <- format(round(nba_gen$raptor_offense, 1), nsmall = 1)
nba_gen$raptor_defense <- format(round(nba_gen$raptor_defense, 1), nsmall = 1)
nba_gen$raptor_total <- format(round(nba_gen$raptor_total, 1), nsmall = 1)
nba_gen$war_total <- format(round(nba_gen$war_total, 1), nsmall = 1)
```

```{r, echo = FALSE}
#rename columns: 
nba_gen <- nba_gen %>% 
  rename(
    PLAYER = player_name,
    TEAM = team,
    MINUTES = mp,
  )

#have to find these on your own
TEAM <- c("ATL", "BOS", "BKN", "CHA", "CHI", "CLE", "DAL", "DEN", "DET",
          "GSW", "HOU", "IND", "LAC", "LAL", "MEM", "MIA", "MIL", "MIN",
          "NOP", "NYK", "OKC", "ORL", "PHI", "PHX", "POR", "SAC", "SAS",
          "TOR", "UTA", "WAS", "PHO", "BRK")
full_name <- c("Hawks", "Celtics", "Nets", "Hornets", "Bulls", "Cavaliers",
          "Mavericks", "Nuggets", "Pistons", "Warriors", "Rockets",
          "Pacers", "Clippers", "Lakers", "Grizzlies", "Heat", "Bucks",
          "Timberwolves", "Pelicans", "Knicks", "Thunder", "Magic",
          "76ers", "Suns", "Blazers", "Kings", "Spurs", "Raptors",
          "Jazz", "Wizards", "Suns", "Nets")

nba_teams <- data.frame(
  TEAM, full_name 
)

nba_gen <- nba_gen %>% 
  left_join(select(nba_teams, TEAM, full_name), by = "TEAM")

nba_gen <- nba_gen[, c("PLAYER", "season", "full_name", "MINUTES", box_score_raptor, on_off_raptor, overall_raptor)]
nba_gen <- nba_gen %>% 
  rename(
    TEAM = full_name
  )

nba_gen$MINUTES <- format(nba_gen$MINUTES,big.mark=", ", trim=TRUE)
nba_gen$season <- nba_gen$season %% 100
```

```{r, echo = FALSE}
#convert columns to numeric:
nba_gen$raptor_box_offense <- as.numeric(nba_gen$raptor_box_offense)
nba_gen$raptor_box_defense <- as.numeric(nba_gen$raptor_box_defense)
nba_gen$raptor_box_total <- as.numeric(nba_gen$raptor_box_total)
nba_gen$raptor_onoff_offense <- as.numeric(nba_gen$raptor_onoff_offense)
nba_gen$raptor_onoff_defense <- as.numeric(nba_gen$raptor_onoff_defense)
nba_gen$raptor_onoff_total <- as.numeric(nba_gen$raptor_onoff_total)
nba_gen$raptor_offense <- as.numeric(nba_gen$raptor_offense)
nba_gen$raptor_defense <- as.numeric(nba_gen$raptor_defense)
nba_gen$raptor_total <- as.numeric(nba_gen$raptor_total)
nba_gen$war_total <- as.numeric(nba_gen$war_total)
```


```{r, echo = FALSE}
blue_pal <- function(x) rgb(colorRamp(c("#fa8072", "white", "#35b0ab"))(x), maxColorValue = 255)

table <- reactable(
  nba_gen,
  columns = list(
    PLAYER = colDef(
      cell = function(value, index) {
        #season <- nba_gen$season[index]
        div(
          class = "player",
          div(
            span(class = "player", value),
            span(class = "season", sprintf(" '22-'%s", nba_gen[index, "season"]),
                 style = list(fontSize = "0.75rem"))
            #div(style = list(fontSize = "0.75rem"), season)
          )
        )
      }
    ),
    season = colDef(show = FALSE),
    
      raptor_offense = colDef(style = function(value) {
      normalized <- (value - min(nba_gen$raptor_offense)) / (max(nba_gen$raptor_offense) - min(nba_gen$raptor_offense))
      color <- blue_pal(normalized)
      list(background = color)
      },
      name = "OFF.",
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_defense = colDef(style = function(value) {
      normalized <- (value - min(nba_gen$raptor_defense)) / (max(nba_gen$raptor_defense) - min(nba_gen$raptor_defense))
      color <- blue_pal(normalized)
      list(background = color)
      },
      name = "DEF.",
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_total = colDef(style = function(value) {
      normalized <- (value - min(nba_gen$raptor_total)) / (max(nba_gen$raptor_total) - min(nba_gen$raptor_total))
      color <- blue_pal(normalized)
      list(background = color)
      
      },
      name = "TOT.",
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_box_offense = colDef(
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      name = "OFF.",
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_box_defense = colDef(
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      name = "DEF.",
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_box_total = colDef(
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      name = "TOT.",
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_onoff_offense = colDef(
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      name = "OFF.",
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_onoff_defense = colDef(
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      name = "DEF.",
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      raptor_onoff_total = colDef(
      cell = function(value) {
        if (value >= 0) paste0("+", value) else value
      },
      name = "TOT.",
      headerStyle = list(fontWeight = "100",
                         fontSize = "0.75rem")),
      
      war_total = colDef(name = "WAR",
                         headerStyle = list(background = "darkgrey",
                                            color = "white",
                                            fontWeight = "700",
                                            fontSize = "0.75rem"),
                         style = function(value, index, name){
                            list(fontWeight = "bold")
                         }
                         )
  ),
  columnGroups = list(
    colGroup(name = "BOX SCORE RAPTOR", columns = box_score_raptor, headerStyle = list(fontSize = "0.75rem")),
    colGroup(name = "ON/OFF RAPTOR", columns = on_off_raptor, headerStyle = list(fontSize = "0.75rem")),
    colGroup(name = "OVERALL RAPTOR", columns = overall_raptor, headerStyle = list(fontSize = "0.75rem"))
  ),
  rownames = TRUE,
  defaultColDef = colDef(headerStyle = list(fontSize = "0.75rem")),
  defaultPageSize = 300
)
table
```


## Scatterplot

```{r}
library(plotly)
```


```{r}
fig <- nba_gen %>% 
  plot_ly(x = ~raptor_offense, y = ~raptor_defense, text = ~paste(PLAYER, " '22-'", season, " ", TEAM,
                                                                  " \n", "Offensive RAPTOR: ", raptor_offense,
                                                                  " \n", "Defensive RAPTOR: ", raptor_defense),
          type = "scatter", mode = "markers") %>% 
  layout(#annotations = list(text = "- offense", x = -9, y = 9, showarrow = FALSE, fill = "pink",
        #                    text = "+ defense", x = -9, y = 8, showarrow = FALSE),
         title = "Where every player in the NBA stands, according to RAPTOR",
         xaxis = list(title = "Offensive RAPTOR rating",
                      range = c(-11, 11),
                      ticktext = list("-10", "-5", "0", "+5", "+10"), 
                      tickvals = list(-10, -5, 0, 5, 10),
                      zerolinecolor = "lightgrey",
                      gridcolor = "lightgrey"),
         yaxis = list(title = "Defensive RAPTOR rating",
                      range = c(-11, 11),
                      ticktext = list("-10", "-5", "0", "+5", "+10"), 
                      tickvals = list(-10, -5, 0, 5, 10),
                      zerolinecolor = "lightgrey",
                      gridcolor = "lightgrey")) 
fig <- fig %>% add_annotations(
  x = -9,
  y = 9,
  text = "- offense",
  showarrow = FALSE,
  bgcolor = "pink"
)
fig <- fig %>% add_annotations(
  x = -9,
  y = 8,
  text = "+ defense",
  showarrow = FALSE,
  bgcolor = "lightblue"
)
fig <- fig %>% add_annotations(
  x = 9,
  y = 9,
  text = "+ offense",
  showarrow = FALSE,
  bgcolor = "lightblue"
)
fig <- fig %>% add_annotations(
  x = 9,
  y = 8,
  text = "+ defense",
  showarrow = FALSE,
  bgcolor = "lightblue"
)
fig <- fig %>% add_annotations(
  x = -9,
  y = -8,
  text = "- offense",
  showarrow = FALSE,
  bgcolor = "pink"
)
fig <- fig %>% add_annotations(
  x = -9,
  y = -9,
  text = "- defense",
  showarrow = FALSE,
  bgcolor = "pink"
)
fig <- fig %>% add_annotations(
  x = 9,
  y = -8,
  text = "+ offense",
  showarrow = FALSE,
  bgcolor = "lightblue"
)
fig <- fig %>% add_annotations(
  x = 9,
  y = -9,
  text = "- defense",
  showarrow = FALSE,
  bgcolor = "pink"
)
fig <- fig %>% 
  add_trace(
    marker = list(
      color = "white",
      size = 10,
      line = list(
        color = "black",
        width = 1.5
      )
  )) 
fig <- fig %>% layout(showlegend = FALSE)
#top right:
fig <- fig %>% layout(
  shapes = list(
    list(
      type = "rect",
      x0 = 0,
      y0 = 0,
      x1 = 10,
      y1 = 10,
      fillcolor = "rgba(173, 216, 230, 0.5)",  
      line = list(
      width = 0
      )
    ),
    list(
      type = "rect",
      x0 = -10,
      y0 = -10,
      x1 = 0,
      y1 = 0,
      fillcolor = "rgba(255, 0, 0, 0.2)", 
      line = list(
      width = 0
      )
    )
  )
)
  
fig
```

sources: https://plotly.com/r/figure-labels/
https://plotly.com/r/plotly-fundamentals/
https://glin.github.io/reactable/articles/womens-world-cup/womens-world-cup.html

























